FROM      lcr.loongnix.cn/library/alpine@sha256:ba4698dc340db5079eea01b7ea3488452a9a1c3cb8aad11033ea2cc978f49ffc
RUN       apk add --no-cache tzdata ca-certificates bash
ARG       APP_NAME=moefile
RUN       mkdir /data
COPY      bin/build/linux/loong64/${APP_NAME}  /app/${APP_NAME}
COPY      scripts/container-init.sh            /app/container-init.sh
WORKDIR   /app
VOLUME    /data
EXPOSE    3328
ENV       APP_NAME=${APP_NAME} \
          LEVEL=inf \
          LISTEN=:3328 \
          ORIGINS=* \
          PROXIES=127.0.0.1 \
          ROOT=/data \
          XMLTAB=true
CMD       ["/app/container-init.sh"]
